#include "SelectIO.h"
#include "gpiointerface.h"


   GPIO_CLOCK_ENABLE(HOST_TX);
   GPIO_CLOCK_ENABLE(HOST_RX);
   GPIO_INIT_AS_ALTERNATE(HOST_TX);
   GPIO_INIT_AS_ALTERNATE(HOST_RX);

   GPIO_CLOCK_ENABLE(GREEN_LED);
   GPIO_INIT_AS_IN(HOST_GREEN);
   GPIO_INIT_AS_OUT(GREEN_LED);

   SETACTIVE(GREEN_LED);
   SETINACTIVE(GREEN_LED);

   SETHIGH(GREEN_LED);
   SETLOW(GREEN_LED);


